version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www
      - ./env/nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    container_name: tt_nginx

  app:
    build:
      context: .
      dockerfile: env/app/Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
        - db
    container_name: tt_app

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "tt_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres_data:/tmp
    ports:
      - "8090:5432"
    container_name: tt_database
    
  redis:
    image: redis:latest
    ports:
      - "8091:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: